version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo_db/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - database:/data/db

volumes:
  database: